### ISSUE TITLE
2.0 Checklist

### ISSUE THREAD

**Issue by yaauie** [resque/redis-namespace#74]
The last 1.x version should support ALL of these changes  when `Redis::Namespace#initialize` is called with `deprecations: true` OR the `REDIS_NAMESPACE_DEPRECATIONS` environment varible set, and should warn unless `Redis::Namespace#initialize` is called with `warnings: false` OR the `REDIS_NAMESPACE_QUIET` environment variable set.

---
- [x] deprecations pathway
  - [x] deprecation path can be enabled with `deprecations: true`
  - [x] deprecation path can be enabled with `REDIS_NAMESPACE_DEPRECATIONS`
  - [x] `deprecations: false` is default
  - [x] warnings pathway
  - [x] warnings path can be disabled with `warnings: false`
  - [x] warnings path can be disabled with `REDIS_NAMESPACE_QUIET`
  - [x] `warnings: true` is default

---
- [x] Don't blindly proxy unknown commands. (#73)
- [ ] Don't allow direct use of non-namespaced commands, but provide a straightforward way to run them when done intentionally, perhaps `Redis::Namespace#without_namespace.flushdb`
  - [ ] select
  - [ ] flushdb
  - [ ] flushall
  - [ ] shutdown ?
  - [ ] script ?
  - [ ] exec
- [x] Guarantee threadsafety for `Redis::Namespace#pipelined` and `Redis::Namespace#multi` (preferably without the use of mutexes, although we can use `Redis#synchronize` if we need to)
- [ ] Avoid `method_missing` altogether, since we know the complete list of supported commands
